name: ModDamage
main: com.moddamage.ModDamage
version: 1.2.0-a3
authors: [KoryuObihiro, ricochet1k, Spudstabber]
description: |
    Completely customize damage in Bukkit with ModDamage!
commands:
  moddamage:
    aliases: [md]
    description: "Basic ModDamage control"
softdepend: [Multiverse-Core, elRegions, WorldGuard, bPermissions, PermissionsBukkit, PermissionsEx, mcMMO, Vault, Votifier]

api-version: 1.13